sudo: require
language: generic
services:
  - docker
before_install:
  - docker build -t surabhiojha12/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true surabhiojha12/docker-react npm run test
